thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfRangeError(())', src/main.rs:123:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfRangeError(())', src/main.rs:146:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
